baseurl = "https://seli-rahmenbau.de"
DefaultContentLanguage = "de"
title = "SeLi Rahmenbau"
theme = "beautifulhugo"
metaDataFormat = "yaml"

[Params]
  homeTitle = "SeLi Rahmenbau" # Set a different text for the header on the home page
  subtitle = "Fahrradrahmen nach Maß aus Stahl und Edelstahl"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = false
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Sebastian Lindler"
  website = "https://seli-rahmenbau.de"
  email = "seli-online@gmx.de"

[[menu.main]]
    name = "Altes"
    url = "https://selirahmenbau.github.io/seli-alt.github.io/index.html"
    weight = 1

[[menu.main]]
    name = "Neues"
    url = "blog"
    weight = 2

[[menu.main]]
    identifier = "rahmenbau"
    name = "Rahmenbau"
    weight = 3

[[menu.main]]
    parent = "rahmenbau"
    name = "Edelstahl"
    url = "page/rahmenbau/edelstahl"
    weight = 1

[[menu.main]]
    parent = "rahmenbau"
    name = "Stahl"
    url = "page/rahmenbau/stahl"
    weight = 2

[[menu.main]]
    parent = "rahmenbau"
    name = "Kurse"
    url = "page/rahmenbau/kurse"
    weight = 3

[[menu.main]]
    name = "Kontakt"
    url = "page/kontakt"
    weight = 4

